const data = {
  cart: [
    {
      product_id: "7",
      price: "1470",
      variant: [],
      variations: [
        {
          name: "Person",
          values: {
            label: ["10"],
          },
        },
      ],
      discount_amount: 34,
      quantity: 1,
      tax_amount: 166.5999999999999,
      add_on_ids: [7, 8],
      add_on_qtys: [1, 1],
    },
  ],
  coupon_discount_amount: 0,
  coupon_discount_title: "",
  order_amount: 1857.6,
  order_type: "delivery",
  delivery_address_id: null,
  payment_method: "cash_on_delivery",
  order_note: "",
  coupon_code: "",
  delivery_time: "now",
  delivery_date: "2025-04-22",
  branch_id: 1,
  distance: -1,
  selected_delivery_area: null,
  delivery_address: {
    id: null,
    address_type: "Home",
    contact_person_number: "+88012345678",
    address: "QCWG+FV8, Moitry Road, Dhaka 1212, Bangladesh",
    latitude: "23.7961739",
    longitude: "90.4272569",
    created_at: null,
    updated_at: null,
    user_id: null,
    _method: null,
    contact_person_name: "Test Developer",
    road: "",
    floor: "",
    house: "",
  },
  is_partial: "0",
  is_cutlery_required: "0",
  bring_change_amount: 0,
  guest_id: "17",
};
